apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: superbowleto
  title: superbowleto
  description: Sistema Responsável pela emissão de boletos no contexto do PSP
  namespace: pagarme-psp
  links:
    - url: "https://github.com/pagarme/superbowleto/blob/master/README.md"
      title: Documentação técnica
      icon: dashboard
  annotations:
    github.com/project-slug: pagarme/superbowleto
    pagar.me/ci: github-actions
    pagar.me/cd: github-actions
    stone.co/sox: "true"
    stone.co/pii: "true"
spec:
  owner: pagarme/processing-banks
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: superbowleto-server
  title: superbowleto-server
  description: Servidor responsável por receber requests http
  namespace: pagarme-psp
  annotations:
    legacy.stone.tech/owner-email: gabriela.leone@pagar.me
    github.com/project-slug: pagarme/superbowleto
    pagar.me/ci: github-actions
    pagar.me/cd: github-actions
    stone.co/sox: "true"
    stone.co/pii: "true"
    legacy.stone.tech/prod-date: "2023-09-25"
    stone.tech/cloud-accounts: aws/pagarme
  labels:
    legacy.stone.tech/internal-user-auth-base: not-applicable
    legacy.stone.tech/access-request-type: service-now-pagarme
    legacy.stone.tech/handle-lgpd: "true"
    legacy.stone.tech/customer-auth-method: not-applicable
    stone.tech/endpoint-type: none
  links:
    - url: https://github.com/pagarme/superbowleto/actions
      title: CD Pipeline
    - url: https://app.datadoghq.com/dashboard/2va-q6a-rni/boleto?refresh_mode=sliding&from_ts=1695666589978&to_ts=1695667489978&live=true
      title: Monitoring
    - url: https://pagarme.app.opsgenie.com/service/list
      title: Incident Manager
spec:
  type: service
  lifecycle: production
  owner: pagarme/processing-banks
  system: superbowleto
  dependsOn:
    - resource:live-superbowleto
    - component:pagarme-gateway/boleto-api-server
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: superbowleto-worker
  title: superbowleto-worker
  description: Worker responsável por receber mensagens do SQS para retentativa de emissão
  namespace: pagarme-psp
  annotations:
    legacy.stone.tech/owner-email: gabriela.leone@pagar.me
    github.com/project-slug: pagarme/superbowleto
    pagar.me/ci: github-actions
    pagar.me/cd: github-actions
    stone.co/sox: "true"
    stone.co/pii: "true"
    legacy.stone.tech/prod-date: "2023-09-25"
    stone.tech/cloud-accounts: aws/pagarme
    grafana/dashboard-selector: DORA
    oculus.stone.tech/configured: "true"
  labels:
    legacy.stone.tech/internal-user-auth-base: not-applicable
    legacy.stone.tech/access-request-type: service-now-pagarme
    legacy.stone.tech/handle-lgpd: "true"
    legacy.stone.tech/customer-auth-method: not-applicable
    stone.tech/endpoint-type: none
  links:
    - url: https://github.com/pagarme/superbowleto/actions
      title: CD Pipeline
    - url: https://app.datadoghq.com/dashboard/2va-q6a-rni/boleto?refresh_mode=sliding&from_ts=1695666589978&to_ts=1695667489978&live=true
      title: Monitoring
    - url: https://pagarme.app.opsgenie.com/service/list
      title: Incident Manager
spec:
  type: service
  lifecycle: production
  owner: pagarme/processing-banks
  system: superbowleto
  dependsOn:
    - resource:live-superbowleto
    - resource:superbowleto-unregistered-boletos
    - component:pagarme-gateway/boleto-api-server
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: live-superbowleto
  title: superbowleto-database
  description: Banco de dados da superbowleto
  namespace: pagarme-psp
  annotations:
    stone.co/sox: "true"
    stone.co/pii: "true"
  labels:
    stone.tech/dbms: postgresql
spec:
  type: database
  owner: pagarme/processing-banks
  system: superbowleto
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: superbowleto-unregistered-boletos
  title: superbowleto-unregistered-boletos
  description: Fila SQS de Boletos Não Registrados
  namespace: pagarme-psp
  annotations:
    github.com/project-slug: pagarme/superbowleto
    stone.co/sox: "true"
    stone.co/pii: "true"
spec:
  type: queue
  owner: pagarme/processing-banks
  system: superbowleto
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: superbowleto
  title: superbowleto
  description: Repositório da superbowleto no Github
  namespace: pagarme-psp
  annotations:
    github.com/project-slug: pagarme/superbowleto
    stone.co/sox: "true"
    stone.co/pii: "true"
spec:
  type: repository
  owner: pagarme/processing-banks
  system: superbowleto
