module.exports = {
  acre: 'ac',
  alagoas: 'al',
  amapá: 'ap',
  amazonas: 'am',
  bahia: 'ba',
  ceará: 'ce',
  'distrito federal': 'df',
  'espírito santo': 'es',
  goiás: 'go',
  maranhão: 'ma',
  'mato grosso': 'mt',
  'mato grosso do sul': 'ms',
  'minas gerais': 'mg',
  pará: 'pa',
  paraíba: 'pb',
  paraná: 'pr',
  pernambuco: 'pe',
  piauí: 'pi',
  'rio de janeiro': 'rj',
  'rio grande do norte': 'rn',
  'rio grande do sul': 'rs',
  rondônia: 'ro',
  roraima: 'rr',
  'santa catarina': 'sc',
  'são paulo': 'sp',
  sergipe: 'se',
  tocantins: 'to',
}
