sequenceDiagram
    participant Client
    participant API
    participant Database

    Client ->>+ API: HTTP GET /boletos/:id
    API ->>+ Database: db.findById(id)
    Database -->>- API: boleto
    API -->>- Client: 200 ok
