sequenceDiagram
    participant Client
    participant API
    participant Database

    Client ->>+ API: HTTP POST /queues
        Note over Client,API: Lambda triggered by: HTTP
        Note over Client,API: Body: (name, queue_url)
    API ->>+ Database: db.create()
    Database -->>- API: "created"
    API -->>- Client: 201 created (queue_id)
