sequenceDiagram
    participant Client
    participant API
    participant Database

    Client ->>+ API: HTTP GET /queues
        Note over Client,API: Lambda triggered by: HTTP
    API ->>+ Database: db.findAll()
    Database -->>- API: queues
    API -->>- Client: 200 ok
