#!usr/bin/env node

const { migrate } = require('../build/functions/database')

console.log('Migration started')

migrate({}, {}, (err) => {
  if (err) {
    console.log('Migration error:')
    console.log(err)
    return
  }

  console.log('Migration completed')
})
